### ISSUE TITLE
Execution failed for task ':document_file_save_plus:compileDebugKotlin'.

### ISSUE THREAD

**Issue by xavit** [advoques/document_file_save_plus#1]
Android Build Failed after upgrade to Flutter 3.0.0.

Execution failed for task ':document_file_save_plus:compileDebugKotlin'.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

**Comment by pontus-jeong** [comment]
#2 this fixed but PR is still not accepted.

**Comment by hayelom123** [comment]
Execution failed for task ':document_file_save_plus:compileReleaseKotlin'.
i am facing the same issue it is not fixed

**Comment by gowthamaravi** [comment]
sorry Guys I'm little busy these days 
I have merged the pull request

**Comment by advoques** [comment]
please check the latest version
